module.exports = {
  _id: '5eb30b6474de5140784a3e01',
  listingId: 6,
  Title: 'Gorgeous Concrete Hat',
  Location: 'South Sincere, Kentucky, Namibia',
  Highlights: [
    {
      _id: '5eb30b6474de5140784a3e02',
      boolean: true,
      title: 'Great check-in experience',
      emblem: 'fas fa-key',
      text: '96% of recent guests gave the check-in process a 5-star rating',
    },
    {
      _id: '5eb30b6474de5140784a3e03',
      boolean: true,
      emblem: 'fas fa-door-open',
      title: 'Self check-in',
      text: 'Check yourself in with the hard drive.',
    },
    {
      _id: '5eb30b6474de5140784a3e04',
      boolean: true,
      emblem: 'fas fa-medal',
      title: 'Percy is a Superhost',
      text: 'Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.',
    },
    {
      _id: '5eb30b6474de5140784a3e05',
      boolean: false,
      emblem: 'fas fa-spray-can',
      title: 'Sparkling clean',
      text: '16 recent guests said this place was sparkling clean.',
    },
    {
      _id: '5eb30b6474de5140784a3e06',
      boolean: false,
      emblem: 'fas fa-map-marker-alt',
      title: 'Great Location',
      text: '93% of recent guests gave the location a 5-star rating',
    },
    {
      _id: '5eb30b6474de5140784a3e07',
      boolean: false,
      emblem: 'fas fa-house-user',
      title: 'Entire home',
      text: 'You’ll have the apartment to yourself.',
    },
  ],
  Owner: 'Percy',
  Image: 'https://overview-images.s3-us-west-2.amazonaws.com/6.jpg',
  Occupancy: 2,
  Bedrooms: 2,
  Beds: 1,
  Bathrooms: 1,
  Info: 'Dolor accusantium laborum. Veniam voluptate illum aliquam. Possimus ea nihil est ad et non minus veniam tempora.',
  MoreInfo: 'Nesciunt recusandae libero non consequatur dolores consectetur consequuntur animi. Et occaecati doloremque a quae dolorum quae sed iusto corporis. Ut facere enim consequatur quidem iusto illum placeat et qui. Omnis excepturi esse est totam deleniti perferendis tempora sed.',
};
